#!/usr/bin/env node
// Merges each army's parts into data/<army>.json and js/data-<army>.js, then cross-checks references.
// Usage: node scripts/build-data.mjs [--strict]
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = (f) => JSON.parse(readFileSync(f, 'utf8'));

const opt = (f, fallback) => (existsSync(f) ? read(f) : fallback);

// One entry per army. Shared core-rules data (force org, core detachments, core rule names) is in data/.
const ARMIES = [
  {
    id: 'necrons', dir: join(root, 'data'), parts: join(root, 'data', 'parts'),
    meta: { name: 'Necrons', source: 'Codex Xenologica – Necrons (Horus Heresy 3rd edition)', version: '1.4.2', date: 'August 2026',
      choice: { label: 'Crypto-Arkana', options: ['Chronomancy', 'Ethermancy', 'Geomancy', 'Plasmancy', 'Psychomancy', 'Technomancy'] } },
    files: { sequelaEffects: 'sequela-effects.json', granted: 'granted-prime-advantages.json', modifiers: 'modifiers.json' },
  },
  {
    id: 'orks', dir: join(root, 'data', 'orks'), parts: join(root, 'data', 'orks', 'parts'),
    meta: { name: 'Orks', source: 'Xenos Forces of the Age of Darkness – Orks (3rd edition rules, Always Strikes First)', version: 'October 2025', date: 'October 2025',
      choice: { label: 'Great Clan', options: ['Bad Moons', 'Blood Axes', 'Deathskulls', 'Evil Sunz', 'Goffs', 'Snakebites', 'Freebooters'],
        sameInDetachment: { exempt: 'Freebooters' } } },
    files: { choiceEffects: 'choice-effects.json', granted: 'granted-prime-advantages.json', modifiers: 'modifiers.json' },
  },
  {
    id: 'drukhari', dir: join(root, 'data', 'drukhari'), parts: join(root, 'data', 'drukhari', 'parts'),
    meta: { name: 'Drukhari', source: 'Codex Xenologica – Drukhari (Horus Heresy 3rd edition)', version: '1.13', date: 'March 2026',
      choice: { label: 'Partisan', options: ['Kabals', 'Cults', 'Covens'] } },
    files: { granted: 'granted-prime-advantages.json', modifiers: 'modifiers.json' },
    // [Combat Drugs]: each unit picks one; every model in the unit gains the bonus (Codex primer, p.3)
    combatDrugs: [
      { name: 'Adrenalight', stat: 'A' }, { name: 'Grave Lotus', stat: 'S' }, { name: 'Hypex', stat: 'I' },
      { name: 'Painbringer', stat: 'T' }, { name: 'Serpentin', stat: 'WS' }, { name: 'Splintermind', stat: 'CL' },
    ],
  },
];

for (const a of ARMIES) a.group = 'Xenos (fan codexes)';

// Armies imported from BSData (scripts/import-bsdata.mjs). Their weapons, wargear and rules text live in one
// shared file, js/data-common.js, which every army loads; the core rules text also fills the fan codexes' gaps.
const BS = join(root, 'data', 'bsdata');
const bsIndex = opt(join(BS, 'armies.json'), { armies: [] });
const common = opt(join(BS, 'common.json'), { weapons: { ranged: [], melee: [] }, wargear: [], rules: { specialRules: [], traits: [], reactions: [], gambits: [] } });
for (const a of bsIndex.armies) {
  ARMIES.push({
    id: a.id, bsdata: true, group: a.group, dir: join(BS, a.id), parts: join(BS, a.id, 'parts'),
    meta: { name: a.name, source: `BSData Horus Heresy 3rd Edition (game system revision ${bsIndex.gameSystemRevision})`, version: `imported ${bsIndex.importedAt}`, date: bsIndex.importedAt,
      choice: { label: '', options: [] }, shared: 'bsdata', skipped: a.skipped },
    files: { granted: 'granted-prime-advantages.json', modifiers: 'modifiers.json' },
  });
}

let failed = false;
const index = [];
for (const army of ARMIES) {
  if (!existsSync(army.parts)) continue;
  const n = build(army);
  index.push({ id: army.id, name: army.meta.name, group: army.group, units: n, ready: army.meta.ready !== false });
}
writeFileSync(join(root, 'js', 'data-common.js'), '/* Generated by scripts/build-data.mjs from data/bsdata/common.json. */\nwindow.ARMY_COMMON = ' + JSON.stringify(common) + ';\n');
writeFileSync(join(root, 'js', 'armies.js'), '/* Generated by scripts/build-data.mjs. */\nwindow.ARMY_INDEX = ' + JSON.stringify(index) + ';\n');
if (failed && process.argv.includes('--strict')) process.exit(1);

function build(army) {
const parts = army.parts;
const files = readdirSync(parts).filter((f) => f.endsWith('.json')).sort();
const out = {
  meta: Object.assign({ id: army.id }, army.meta),
  units: [], lists: [], arkana: [], weapons: { ranged: [], melee: [] }, wargear: [],
  rules: { specialRules: [], reactions: [], gambits: [], primeAdvantages: [], traits: [], powersOfTheCtan: [], unitTypes: [] },
  detachments: [], sequelae: { intro: '', sequelae: [] }, faq: [], baseSizes: [],
  forceorg: read(join(root, 'data', 'forceorg.json')),
  coreRules: read(join(root, 'data', 'core-rules.json')),
  sequelaEffects: army.files.sequelaEffects ? opt(join(army.dir, army.files.sequelaEffects), { effects: [], rules: [] }) : { effects: [], rules: [] },
  choiceEffects: army.files.choiceEffects ? opt(join(army.dir, army.files.choiceEffects), { effects: [] }) : { effects: [] },
  grantedPrimeAdvantages: opt(join(army.dir, army.files.granted), { grantedPrimeAdvantages: [] }).grantedPrimeAdvantages,
  modifiers: opt(join(army.dir, army.files.modifiers), { modifiers: [] }),
};
// the shared file holds core rule names plus the Necron codex's own gaps; other armies bring theirs
const own = opt(join(army.dir, 'codex-notes.json'), { undefinedInCodex: [], weaponAliases: {} });
if (army.id !== 'necrons') out.coreRules = Object.assign({}, out.coreRules, { undefinedInCodex: own.undefinedInCodex || [], weaponAliases: own.weaponAliases || {} });

for (const f of files) {
  const d = read(join(parts, f));
  if (d.units) out.units.push(...d.units);
  if (d.lists) out.lists.push(...d.lists);
  if (d.arkana) out.arkana.push(...d.arkana);
  if (d.ranged) out.weapons.ranged.push(...d.ranged);
  if (d.melee) out.weapons.melee.push(...d.melee);
  if (d.wargear) out.wargear.push(...d.wargear);
  for (const k of Object.keys(out.rules)) if (d[k]) out.rules[k].push(...d[k]);
  if (d.detachments) out.detachments.push(...d.detachments);
  if (d.sequelae) { out.sequelae.sequelae.push(...d.sequelae); if (d.intro) out.sequelae.intro = d.intro; }
  if (d.faq) out.faq.push(...d.faq);
  if (d.baseSizes) out.baseSizes.push(...d.baseSizes);
}

// Combat Drugs: a required pick on every unit with the trait, and a +1 modifier per drug
if (army.combatDrugs) {
  for (const u of out.units) {
    // "May be upgraded to have the [Combat Drugs] trait": the drug pick is required once the upgrade is taken
    const buy = (u.options || []).find((o) => (o.choices || []).some((c) => c.name === '[Combat Drugs]'));
    if (buy && !u.combatDrugs) {
      u.options.push({
        id: 'combat-drug-choice', kind: 'one', model: null, replaces: [], required: {}, requires: buy.id,
        text: 'Choose the Combat Drug for the [Combat Drugs] upgrade.',
        choices: army.combatDrugs.map((d) => ({ name: d.name, points: 0 })),
      });
      continue;
    }
    if (!u.combatDrugs) continue;
    if (u.fixedDrug) { for (const m of u.models) m.wargear = (m.wargear || []).concat(u.fixedDrug); continue; }
    u.options = (u.options || []).concat({
      id: 'combat-drugs', kind: 'one', model: null, replaces: [], required: {},
      text: '[Combat Drugs]: one Combat Drug must be selected for this Unit. Every model in the Unit gains its bonus.',
      choices: army.combatDrugs.map((d) => ({ name: d.name, points: 0 })),
    });
  }
  for (const d of army.combatDrugs) {
    out.modifiers.modifiers.push({ id: `combat-drug-${d.name.toLowerCase().replace(/\W+/g, '-')}`, page: 3, text: `${d.name}: +1 ${d.stat}.`,
      source: { type: 'upgrade', name: d.name }, appliesTo: {}, scope: 'unit', stats: { [d.stat]: '+1' } });
    out.rules.traits.push({ name: d.name, page: 3, text: `Combat Drug. Models in a Unit with this Trait gain +1 ${d.stat}.` });
  }
}

// core detachments from the Horus Heresy rulebook sit alongside the codex ones
out.detachments.push(...(out.forceorg.detachments || []));

// ---------- checks ----------
const problems = [];
const warn = [];
const ids = new Set();
const listIds = new Set(out.lists.map((l) => l.id));
const { norm, wkey } = require(join(root, 'js', 'engine.js'));
const coreFile = out.coreRules;
const coreNames = [...coreFile.rules, ...coreFile.undefinedInCodex.map((x) => x.name)];
const core = new Set([...coreNames.map(norm), ...coreNames.map(wkey)]);
const aliases = new Map(Object.entries(coreFile.weaponAliases || {}).map(([k, v]) => [wkey(k), wkey(v)]));
const weaponKeys = new Set([...out.weapons.ranged, ...out.weapons.melee].map((w) => wkey(w.name)));
const ruleKeys = new Set();
// rules text shared from BSData (core special rules, traits, reactions)
for (const k of Object.keys(common.rules)) for (const r of common.rules[k]) ruleKeys.add(norm(r.name));
for (const w of common.wargear) ruleKeys.add(norm(w.name));
if (army.bsdata) for (const w of [...common.weapons.ranged, ...common.weapons.melee]) weaponKeys.add(wkey(w.name));
for (const k of Object.keys(out.rules)) for (const r of out.rules[k]) ruleKeys.add(norm(r.name));
for (const w of out.wargear) ruleKeys.add(norm(w.name));
for (const a of out.arkana) { if (a.harbinger) ruleKeys.add(norm(a.harbinger.name)); for (const w of a.wargear || []) ruleKeys.add(norm(w.name)); }

for (const e of out.choiceEffects.effects || []) for (const c of (e.option && e.option.choices) || []) if (c.name) ruleKeys.add(norm(c.name));

const KINDS = new Set(['one', 'any', 'perModel', 'swapModel', 'upgrade']);
const ROLES = new Set(['Warlord', 'High Command', 'Command', 'Retinue', 'Elites', 'War Engine', 'Troops', 'Support', 'Transport', 'Heavy Assault', 'Heavy Transport', 'Armour', 'Recon', 'Fast Attack', 'Lord of War', 'Fortification']);

for (const u of out.units) {
  const where = `${u.id || u.name}`;
  if (!u.id) problems.push(`${where}: missing id`);
  if (ids.has(u.id)) problems.push(`${where}: duplicate id`);
  ids.add(u.id);
  if (!ROLES.has(u.role)) problems.push(`${where}: unknown role "${u.role}"`);
  if (typeof u.basePoints !== 'number') problems.push(`${where}: basePoints not a number`);
  if (!Array.isArray(u.models) || !u.models.length) problems.push(`${where}: no models`);
  for (const r of u.unitRules || []) ruleKeys.add(norm(r.name));
  const modelNames = new Set((u.models || []).map((m) => m.name));
  const optIds = new Set();
  for (const o of u.options || []) {
    if (optIds.has(o.id)) problems.push(`${where}: duplicate option id ${o.id}`);
    optIds.add(o.id);
    if (!KINDS.has(o.kind)) problems.push(`${where}/${o.id}: unknown kind ${o.kind}`);
    if (o.model && !modelNames.has(o.model)) problems.push(`${where}/${o.id}: option model "${o.model}" not in models`);
    if (!o.choices || !o.choices.length) problems.push(`${where}/${o.id}: no choices`);
    for (const c of o.choices || []) {
      if (c.list && !listIds.has(c.list) && !['arkana-weapons', 'techno-arkana'].includes(c.list)) problems.push(`${where}/${o.id}: unknown list ${c.list}`);
      if (!c.list && typeof c.points !== 'number') problems.push(`${where}/${o.id}: choice "${c.name}" has non-numeric points`);
    }
    if (o.kind === 'swapModel' && !modelNames.has(o.choices?.[0]?.name)) problems.push(`${where}/${o.id}: swap target "${o.choices?.[0]?.name}" not in models`);
    if (o.requires && !(u.options || []).some((x) => x.id === o.requires)) problems.push(`${where}/${o.id}: requires unknown option ${o.requires}`);
  }
}

// sequela effects must point at real units, lists and sequelae
const seqNames = new Set(out.sequelae.sequelae.map((x) => x.name));
for (const e of out.sequelaEffects.effects) {
  if (!seqNames.has(e.sequela)) problems.push(`sequela effect: unknown sequela "${e.sequela}"`);
  for (const id of e.units || []) if (!ids.has(id)) problems.push(`sequela effect ${e.sequela}: unknown unit ${id}`);
  if (e.list && !listIds.has(e.list)) problems.push(`sequela effect ${e.sequela}: unknown list ${e.list}`);
  for (const c of (e.option && e.option.choices) || []) if (c.list && !listIds.has(c.list)) problems.push(`sequela effect ${e.sequela}: unknown list ${c.list}`);
}
for (const r of out.sequelaEffects.rules || []) ruleKeys.add(norm(r.name));

// modifiers must point at real units and models
const allModels = new Set(out.units.flatMap((u) => u.models.map((m) => m.name)));
const STAT_KEYS = new Set(['M', 'WS', 'BS', 'S', 'T', 'W', 'I', 'A', 'LD', 'CL', 'WP', 'IN', 'SAV', 'INV', 'FRONT', 'SIDE', 'REAR', 'HP']);
for (const m of out.modifiers.modifiers) {
  const where = `modifier ${m.id}`;
  if (!['sequela', 'wargear', 'arkana', 'primeAdvantage', 'upgrade', 'unitRule'].includes(m.source?.type)) problems.push(`${where}: bad source type`);
  if (m.source?.type === 'sequela' && !seqNames.has(m.source.name)) problems.push(`${where}: unknown sequela ${m.source.name}`);
  for (const id of m.appliesTo?.units || []) if (!ids.has(id)) problems.push(`${where}: unknown unit ${id}`);
  for (const n of m.appliesTo?.models || []) if (!allModels.has(n)) problems.push(`${where}: unknown model ${n}`);
  for (const k of Object.keys(m.stats || {})) if (!STAT_KEYS.has(k)) problems.push(`${where}: unknown stat ${k}`);
  if (!['model', 'unit'].includes(m.scope)) problems.push(`${where}: scope must be model or unit`);
}

// second pass: references to weapons / rules (warnings only)
for (const u of out.units) {
  const hasWeapon = (w) => weaponKeys.has(aliases.get(wkey(w)) || wkey(w)) || weaponKeys.has(wkey(w).replace(/^twin(-linked)? /, ''));
  for (const m of u.models || []) for (const w of m.wargear || []) if (!hasWeapon(w) && !ruleKeys.has(norm(w)) && !core.has(norm(w)) && !core.has(wkey(w))) warn.push(`${u.id}: wargear "${w}" has no weapon profile or wargear text`);
  for (const r of [...(u.specialRules || []), ...(u.models || []).flatMap((m) => m.specialRules || [])]) {
    if (!ruleKeys.has(norm(r)) && !core.has(norm(r))) warn.push(`${u.id}: rule "${r}" has no text`);
  }
}
for (const l of out.lists) for (const it of l.items) if (!weaponKeys.has(wkey(it.name)) && !weaponKeys.has(wkey(it.name).replace(/^twin(-linked)? /, '')) && !ruleKeys.has(norm(it.name)) && !core.has(norm(it.name))) warn.push(`list ${l.id}: "${it.name}" has no profile or text`);

if (!army.bsdata) writeFileSync(join(root, 'data', `${army.id}.json`), JSON.stringify(out, null, 1) + '\n');
writeFileSync(join(root, 'js', `data-${army.id}.js`), `/* Generated by scripts/build-data.mjs from ${army.parts.slice(root.length + 1)} — edit those files instead. */\nwindow.ARMY_DATA = window.ARMY_DATA || {};\nwindow.ARMY_DATA[${JSON.stringify(army.id)}] = ` + JSON.stringify(out) + ';\n');

console.log(`[${army.id}] units ${out.units.length}, lists ${out.lists.length}, ranged ${out.weapons.ranged.length}, melee ${out.weapons.melee.length}, wargear ${out.wargear.length}, rules ${Object.values(out.rules).reduce((a, b) => a + b.length, 0)}, detachments ${out.detachments.length}, sequelae ${out.sequelae.sequelae.length}`);
if (warn.length && !army.bsdata) console.log(`\n${warn.length} reference warnings:\n  ` + [...new Set(warn)].join('\n  '));
else if (warn.length) console.log(`  ${new Set(warn).size} reference warnings (BSData import; not listed)`);
if (problems.length) {
  console.error(`\n[${army.id}] ${problems.length} problems:\n  ` + problems.join('\n  '));
  failed = true;
}
return out.units.length;
}
